import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = async ({ children }) => {
  const response = await fetch(`${process.env.API_HOST}/socials/`);
  const socials = await response.json();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          <div>
            <Suspense fallback="Loading...">
              {children}
            </Suspense>
          </div>
        </main>
        <Footer socials={socials} />
      </body>
    </html>
  );
}

export default RootLayout;
