import Link from "next/link";
import Heading from "@/components/heading";
import { IContact } from "@/types/contact";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contacts",
  description: "Generated by create next app",
};

const Contacts: React.FC = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/users");
  const contacts: IContact[] = await response.json();

  if (!contacts) {
    return <Heading text="No contacts found" />
  }

  return (
    <>
      <Heading text="Contact list:" />
      <ul>
        {contacts.map(({ id, name, email }) => {
          return (
            <li key={id}>
              <Link href={`/contacts/${id}`}>{name} ({email})</Link>
            </li>
          )
        })}
      </ul>
    </>
  )
}

export default Contacts;
