import { Params } from "next/dist/shared/lib/router/utils/route-matcher";
import ContactInfo from "@/components/contact-info";
import { IContact } from "@/types/contact";
import BackButton from "@/components/back-button";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

interface ContactProps { 
  params: Params
}

const Contact: React.FC<ContactProps> = async ({ params }) => {
  const response = await fetch(`https://jsonplaceholder.typicode.com/users/${params.slug}`);
  const contact: IContact = await response.json();

  return (
    <>
      <BackButton />
      <ContactInfo contact={contact} />
    </>
  )
}

export default Contact;
